### ISSUE TITLE
rocker/ml-verse: could not find a Python environment 

### ISSUE THREAD

**Issue by Marketos-Damigos** [rocker-org/rocker-versioned2#303]
First of all a big thank you for maintaining this project, been using it for more than a year and it is great.

Some days ago I decided to experiment with version `rocker/ml-verse:cuda11` and install tensorflow as described from the [official rstudio tutorial](https://tensorflow.rstudio.com/installation/gpu/local_gpu/). I had a fully working version of `rocker/verse`, changed by docker-compose and pulled  `rocker/ml-verse:cuda11`. The installation worked perfectly until i run a model with gpu. I got an error for mismatch of cudnn as described also in #235 . 

I started from scratch with deleting everything and now when i run `install_tensorflow(version = "gpu")` i receive the following message: `Error: could not find a Python environment for /usr/bin/python3.8`

I have selected python 3.8 from settings already and i can run python if i create i python script. I even run the python and tensorflow installation script inside rocker_scripts

Edit: After rebooting my server and running everything from scratch, with using virualenv from settings, i get: 

```
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/opt/venv/reticulate/lib/python3.8/site-packages/urllib3'
Check the permissions.

Error: Error installing package(s): "'tensorflow==2.7.*'"
```
Also my docker-compose looks like this: 

```
rstudio:
    image: rocker/ml-verse:cuda11.1
    container_name: rocker
    environment:
      - PASSWORD=######################
      - PUID=1000
      - PGID=1000
      - ROOT=TRUE
    networks:
      web:
        ipv4_address: ############
    volumes:
      -###############:/home
    restart: always
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
```
