### ISSUE TITLE
Shiny Server don't respect the container environment variables

### ISSUE THREAD

**Issue by eitsupi** [rocker-org/rocker-versioned2#318]
I was creating a docker-compose project to link multiple containers as shown below, and had trouble with the timezone setting not being reflected in the shiny app.

```yml
version: "3.8"

x-common_environment: &common_environment
  TZ: Asia/Tokyo

services:
  db:
    image: postgres:13
    environment:
      <<: *common_environment

  shiny:
    image: rocker/shiny:4
    environment:
      <<: *common_environment
    ports:
      - 3838:3838
```

I think it is worthwhile to make the same changes to Shiny Server that were once made to containers with RStudio Server installed (#186).
I think it can be achieved by simply copying the following lines from `userconf.sh` and pasting it into `install_shiny_server.sh`.

https://github.com/rocker-org/rocker-versioned2/blob/071c6a3e3eabe0eb36706fc6f50df477ca41abc7/scripts/userconf.sh#L106-L112

Like these lines.

https://github.com/rocker-org/rocker-versioned2/blob/071c6a3e3eabe0eb36706fc6f50df477ca41abc7/scripts/install_shiny_server.sh#L49-L57
