### ISSUE TITLE
Running rocker/shiny as shiny user (non root)  in Kubernetes cluster failing

### ISSUE THREAD

**Issue by adamlepkowski** [rocker-org/rocker-versioned2#366]
Hello,

I created my own dockerfile which utilize rocker/shiny:4.1.1 as a base image. I try to execute the image in Kubernetes cluster (Azure Kubernetes Services) and I get the following exception:
`s6-mkdir: warning: unable to mkdir /var/run/s6: Permission denied`

I know that this topic was discussed many times in the following tickets:
1. https://github.com/rocker-org/rocker-versioned2/issues/360
2. https://github.com/rocker-org/shiny/issues/79
3. https://github.com/rocker-org/rocker-versioned2/issues/81
4. https://github.com/randy3k/shiny-cloudrun-demo/issues/2 (gcp)

Dockerfile (based on the solution reported in the above issues):

```
FROM rocker/shiny:4.1.2 AS base 
# testerd with 4.1.2, 4.1.1, 4.1.0

FROM base AS build
WORKDIR /srv/shiny-server
COPY ["app.R", "/srv/shiny-server/"]

USER shiny

# avoid s6 initialization
# see https://github.com/rocker-org/shiny/issues/79
CMD ["/usr/bin/shiny-server"]

```
As you can see above S6 shouldn't be initialized because of CMD command.

My pod definition contains the following security context:
```
runAsNonRoot: true
runAsUser: 999 #shiny user
allowPrivilegeEscalation : false
```
If I remove `allowPrivilegeEscalation : false` or set `allowPrivilegeEscalation : true` then it's working becasue S6 needs root privilages but I don't want to initialize S6 at all.

If I execute my custom image in docker everything is working (based on the logs I assume S6 is not initialized):
Command: 
`docker run --user shiny  -p 3838:3838 "hello-world-shiny"`
Result:
```
[2022-02-25T07:33:07.717] [INFO] shiny-server - Shiny Server v1.5.18.979 (Node.js v12.22.6)
[2022-02-25T07:33:07.727] [INFO] shiny-server - Using config file "/etc/shiny-server/shiny-server.conf"
[2022-02-25T07:33:07.781] [INFO] shiny-server - Starting listener on http://[::]:3838

```

Any idea what is going on?

**Comment by adamlepkowski** [comment]
The problem is connected with Azure Kubernetes Services.  If we specify `CMD ["/usr/bin/shiny-server"]` in our dockerfile this CMD is not taken into consideration because in the base image there is a CMD statement (https://github.com/rocker-org/rocker-versioned2/blob/master/dockerfiles/shiny_4.1.2.Dockerfile).

When the image is executed in the docker the last CMD is taken into consideration and that's why it's working. The only solution to make it work with AKS is to specify the command in the pod definition:

```
apiVersion: v1
kind: Pod
metadata:
  name: "hello-world"
  namespace: shinyproxy
  labels:
    app: "hello-world"
spec:
  containers:
  - name: hello-world
    image: "..../shiny-hello-world:test"
    command: ["/usr/bin/shiny-server"]
    securityContext:
      runAsNonRoot: true
      runAsUser: 999
      allowPrivilegeEscalation : false
```
