### ISSUE TITLE
Path prefix does not work as expected with RStudio server and Traefik

### ISSUE THREAD

**Issue by rlaiola** [rocker-org/rocker-versioned2#388]
### What is this issue about?

Some users have reported difficulties to setup RStudio server with Traefik reverse proxy using a path prefix (e.g., www.example.com/rstudio). The reference discussions are linked below:

- https://community.traefik.io/t/traefik-and-rstudio/9003
- https://community.traefik.io/t/traefik-and-rstudio-reverse-proxy/10304

The problem occurs because not only Traefik, but also Rstudio server must be configured accordingly.

#### 1. Basic example: does NOT work
_docker-compose.yml_

````yml
version: "3.3"

services:

  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  # RStudio server
  rstudio:
    image: "rocker/rstudio:latest"
    # IMPORTANT: this name MUST be used in traefik's routers service
    container_name: "rstudio-server"
    restart: "unless-stopped"
    environment:
      - PASSWORD=rstudio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rstudio-server.rule=Host(`localhost`) && PathPrefix(`/rstudio`)"
      - "traefik.http.routers.rstudio-server.entrypoints=web"
      - "traefik.http.services.rstudio-server.loadbalancer.server.port=8787"
````

1. Open a Terminal window (e.g., Bash) and run the following command:
`docker-compose up -d`
1. Open a Web browser window and visit the URL http://localhost/rstudio. The login screen will not be rendered as expected.
    <img width="689" alt="Screen Shot 2022-03-14 at 09 29 14" src="https://user-images.githubusercontent.com/4059310/158252984-8a5830e0-5152-41eb-b5c1-ba8b54dc296d.png">
1. To stop it:
`docker-compose down`

#### 2. Stripping prefix (Traefik): still does NOT work
_docker-compose.yml_

````yml
version: "3.3"

services:

  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  # RStudio server
  rstudio:
    image: "rocker/rstudio:latest"
    # IMPORTANT: this name MUST be used in traefik's routers service
    container_name: "rstudio-server"
    restart: "unless-stopped"
    environment:
      - PASSWORD=rstudio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rstudio-server.rule=Host(`localhost`) && PathPrefix(`/rstudio`)"
      - "traefik.http.routers.rstudio-server.entrypoints=web"
      - "traefik.http.middlewares.rstudio-server-path-strip.stripprefix.prefixes=/rstudio"
      - "traefik.http.middlewares.rstudio-server-path-strip.stripprefix.forceSlash=false"
      - "traefik.http.routers.rstudio-server.middlewares=rstudio-server-path-strip"
      - "traefik.http.services.rstudio-server.loadbalancer.server.port=8787"
````

1. Open a Terminal window and run the following command:
`docker-compose up -d`
1. Open a Web browser window and visit the URL http://localhost/rstudio. Although Rstudio server manages to find the entry path, the login screen is not rendered as expected (it cannot find resources).
    <img width="689" alt="Screen Shot 2022-03-14 at 09 42 12" src="https://user-images.githubusercontent.com/4059310/158253079-abae6514-9531-42c3-91c3-8d02baeda674.png">
1. To stop it:
`docker-compose down`

### How to fix it?
The problem occurs because RStudio server does not know what path it is being served from. One can find all RStudio Server Configuration [here](https://docs.rstudio.com/ide/server-pro/latest/rstudio-server-configuration.html). In order to fix this issue it is necessary to set the www Setting `www-root-path` in _`/etc/rstudio/rserver.conf`_ to match the proxy prefix (e.g., /rstudio).

_wwwsettings.sh_

````bash
#!/usr/bin/with-contenv bash

## RStudio Server Configuration
## https://docs.rstudio.com/ide/server-pro/latest/rstudio-server-configuration.html

## www Settings

# www-root-path: The path prefix added by a proxy to the incoming RStudio URL. 
# This setting is used so RStudio Server knows what path it is being served
# from. If running RStudio Server behind a path-modifying proxy, this should
# be changed to match the base RStudio Server URL.
if [ -n "$WWW_ROOT_PATH" ]; then
  # echo "www-root-path=$WWW_ROOT_PATH"
  echo "www-root-path=$WWW_ROOT_PATH" >> /etc/rstudio/rserver.conf
fi
````

_docker-compose.yml_ (**NOTE: /home/dev/wwwsettings.sh is an absolute path on the host machine and must be modified accordingly**)

````yml
version: "3.3"

services:

  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  # RStudio server
  rstudio:
    image: "rocker/rstudio:latest"
    # IMPORTANT: this name MUST be used in traefik's routers service
    container_name: "rstudio-server"
    restart: "unless-stopped"
    environment:
      - PASSWORD=rstudio
      # Set the path prefix added by Traefik to the incoming RStudio URL.
      # https://docs.rstudio.com/ide/server-pro/latest/rstudio-server-configuration.html
      - WWW_ROOT_PATH=/rstudio
    volumes:
      - "/home/dev/wwwsettings.sh:/etc/cont-init.d/wwwsettings"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rstudio-server.rule=Host(`localhost`) && PathPrefix(`/rstudio`)"
      - "traefik.http.routers.rstudio-server.entrypoints=web"
      - "traefik.http.middlewares.rstudio-server-path-strip.stripprefix.prefixes=/rstudio"
      - "traefik.http.middlewares.rstudio-server-path-strip.stripprefix.forceSlash=false"
      - "traefik.http.routers.rstudio-server.middlewares=rstudio-server-path-strip"
      - "traefik.http.services.rstudio-server.loadbalancer.server.port=8787"
````

1. Open a Terminal window and run the following command:
  `docker-compose up -d`
1. Open a Web browser window, visit the URL http://localhost/rstudio and voilà!
    <img width="689" alt="Screen Shot 2022-03-14 at 09 49 35" src="https://user-images.githubusercontent.com/4059310/158257556-68080e20-e5d7-4e67-9683-939c9dda2fe6.png">
1. To stop it:
`docker-compose down`

To allow the deployment of RStudio Server on a self-service container service delivery platform (e.g., Portainer) with no need to mount a volume I'd suggest to place the content of _`wwwsettings.sh`_ in _`rocker-versioned2/scripts/init_set_env.sh`_ (or in _`rocker-versioned2/scripts/init_userconf.sh`_).

https://github.com/rocker-org/rocker-versioned2/blob/83651a7f3471d0f56f73bfaff462191e42eeeb1d/scripts/init_set_env.sh#L1-L14

In the future, it may be relevant to expose other RStudio server configuration settings/properties. Just let me know in case I should send the proposed solution as a pull request.

Cheers!

**Comment by eitsupi** [comment]
The ability to change the base URL with an environment variable is common in Docker images and makes sense.
It would be better to add a new init script specifically for this purpose rather than adding it to an existing init script (init_env or init_userconf).

**Comment by saepire** [comment]
I believe this can be solved entirely without rstudio configuration but externally by a reverse proxy. I stumbled onto this while doing something similar and you can use the `X-RStudio-Root-Path` header to inform rstudio where it is being served from. No need to bother with the environment root prefix variable. I'm using caddy and adding that header to a reverse proxy looks like this:

```
header_up X-RStudio-Root-Path /rstudio
```

You can make the path deeper if you like in the same manner. One **important note**, if you route to rstudio under a prefix, e.g. `/rstudio` inside a cluster or a nested reverse proxy, DO strip such prefix `/rstudio` with traefik so that rstudio receives requests at root `/`.

**Comment by rlaiola** [comment]
> I believe this can be solved entirely without rstudio configuration but externally by a reverse proxy. I stumbled onto this while doing something similar and you can use the `X-RStudio-Root-Path` header to inform rstudio where it is being served from. No need to bother with the environment root prefix variable. I'm using caddy and adding that header to a reverse proxy looks like this:
> 
> ```
> header_up X-RStudio-Root-Path /rstudio
> ```
> 
> You can make the path deeper if you like in the same manner. One **important note**, if you route to rstudio under a prefix, e.g. `/rstudio` inside a cluster or a nested reverse proxy, DO strip such prefix `/rstudio` with traefik so that rstudio receives requests at root `/`.

@saepire I did what you recommended and managed to get it working with the latest image. No further changes needed! The `docker-composer.yml` script follows:

````yml
version: "3.3"

services:

  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  # RStudio server
  rstudio:
    image: "rocker/rstudio:latest"
    # IMPORTANT: this name MUST be used in traefik's routers service
    container_name: "rstudio-server"
    restart: "unless-stopped"
    environment:
      - PASSWORD=rstudio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rstudio-server.rule=Host(`localhost`) && PathPrefix(`/rstudio`)"
      - "traefik.http.routers.rstudio-server.entrypoints=web"
      - "traefik.http.middlewares.rstudio-server-path-strip.stripprefix.prefixes=/rstudio"
      - "traefik.http.middlewares.rstudio-server-path-strip.stripprefix.forceSlash=false"
      - "traefik.http.middlewares.rstudio-server-root-path-header.headers.customrequestheaders.X-RStudio-Root-Path=/rstudio"
      - "traefik.http.routers.rstudio-server.middlewares=rstudio-server-root-path-header,rstudio-server-path-strip"
      - "traefik.http.services.rstudio-server.loadbalancer.server.port=8787"
````

1. Open a Terminal window and run the following command (considering the `docker-compose.yml` is in the same folder):
`docker-compose up -d`
1. Open a Web browser window and visit the URL http://localhost/rstudio. The login screen is presented as expected.
    ![Screen Shot 2022-12-21 at 14 42 13](https://user-images.githubusercontent.com/4059310/208969839-5c4fc082-cfbf-4530-9180-017e90a319d3.png)
1. To stop it, run:
`docker-compose down`

Cheers!
