### ISSUE TITLE
Permission of volume with Shiny Server

### ISSUE THREAD

**Issue by vanhry** [rocker-org/rocker-versioned2#485]
I have my docker container with shiny application

To be able to save file in `files` folder (with `shiny` user which run application) I do this in my **DOCKERFILE**:

`RUN chown shiny:shiny /srv/shiny-server/files`

Then I switch to the shiny user:

`USER shiny`

If I run docker with `docker run` all ownerships are fine, same they were set in **DOCKERFILE**

As soon as I use **docker-compose.yml** with **external** volume:

Also I mount this volume to other services, and want it to be **shared** between all of this containers

```yml
volumes:
      - volume_test:/srv/shiny-server/files
```
It changes back the ownership of **srv/shiny-server/files** directory to **root**. It's important to me to be able to use **docker-compose.yml** and run app with **shiny** user

What didn't help for me

- Setting the `user:shiny` in **docker-compose.yml**
- Change the permission of **Mountpoint** from `docker volume inspect volume_test`

Ideas:

- Maybe it is possible to create this volume inside DOCKERFILE, but how to make it shared between all containers?

Have anybody faced with similar problem?

**Comment by eitsupi** [comment]
I can't reproduce this.

I tested a compose file.

```yml
services:
  r:
    build:
      context: .
    user: shiny
    volumes:
      - test:/srv/shiny-server/files
    working_dir: /srv/shiny-server/files

volumes:
  test:
```

with this Dockefile

```dockerfile
FROM rocker/shiny:4

RUN mkdir /srv/shiny-server/files \
    && chown shiny:shiny /srv/shiny-server/files
```

log in to the container.

```sh
docker compose up -d
docker compose exec r bash
```

create a file.

```sh
touch foo
```

**Comment by vanhry** [comment]
I changed your example a little bit to reproduce my issue

And I don't understand why but this example works unlike my code.

But one problem still exists it's subdirectories of `files` folder, in the example below ownership of `files` is correct, but subdirectories have 'root' owner

Dockerfile
```Dockerfile
FROM rocker/shiny:4

RUN rm -r /srv/shiny-server/*

# there are Dockerfile, docker-compose.yml and files/f1 directories in "."
COPY . /srv/shiny-server

RUN chown shiny:shiny /srv/shiny-server/files
RUN chown shiny:shiny /srv/shiny-server/files/f1

USER shiny

EXPOSE 3838

CMD ["/usr/bin/shiny-server"]
```

docker-compose:
```yml
version: '3'
services:
  rservice:
    image: builded/image1
    user: shiny
    volumes:
      - test:/srv/shiny-server/files
    networks:
      - test_net

volumes:
  test:

networks:
  test_net:
    external: true
```
