### ISSUE TITLE
Kubernetes and environment variables not setting password for RStudio

### ISSUE THREAD

**Issue by genignored** [rocker-org/rocker-versioned2#508]
### Container image name

rocker/rstudio:latest

### What operating system are you seeing the problem on?

Linux

### System information

- Docker  19.03.15
- Kubernetes 1.18.15

### Bug description

Trying to set up a simple implementation of kubernetes using the rocker/rstudio docker images.  

We are unable to run any configuration in which setting the PASSWORD environment variable for kubernetes correctly starts the docker image such that the actual password for the Rstudio instance is set to that env variable.  

I am not sure if it's a bug in the kubernetes yaml file, or if there is some other issue causing this.  

attached yaml file.

The behavior is that no matter how I supply PASSWORD, it is not set during the rstudio startup, but only for kubernetes (docker run works fine)

### How to reproduce this bug?

```sh
kubectl apply -f rstudio.yaml  
```

rstudio.yaml

```yml
apiVersion: v1
kind: Service
metadata:
  name: rstudio
  labels:
    app: rstudio
spec:
  ports:
  - port: 8787
    protocol: TCP
    targetPort: 8787
  selector:
    app: rstudio
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rstudio
  labels:
    app: rstudio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rstudio
  template:
    metadata:
      labels:
        app: rstudio
    spec:
      containers:
      - name : rstudio
        image: rocker/rstudio
        env:
          - name: PASSWORD
            value: "hello_world"
          - name: DISABLE_AUTH
            value: "true"
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8787
          protocol: TCP
        command:
         - "/bin/bash"
         - "-c"
         - "--"
        args :
         - 'rstudio-server start ; sleep infinity'
```
