### ISSUE TITLE
rstudio in kubernetes - runAsNonRoot context

### ISSUE THREAD

**Issue by radhupr** [rocker-org/rocker-versioned2#888]
### Container image name

rocker/rstudio:4.4.2

### What operating system are you seeing the problem on?

Linux

### System information

Kubernetes cluster 1.30
Docker image : rocker/rstudio:4.4.2

### Bug description

Hi Team,
I want to run rstudio server (free version) on kubernetes. If I'm taking wrong approach here, please guide me on how to do the setup in kubernetes.
I'm using the image rocker/rstudio:4.4.2 and trying to run it as nonRoot user. (same noted with image rocker/tidyverse:4.4.2)
The pod spec is as follows 
```
spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1001
        runAsGroup: 1001
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name : rstudio
        image:  rocker/tidyverse:4.4.2
        env:
          - name: USERID
            value: "1001"
          - name: GROUPID
            value: "1001"
        securityContext:
          allowPrivilegeEscalation: false
        resources:  
          requests:
            memory: "200Mi"  
            cpu: "3000m"     
          limits:
            memory: "5000Mi"
``` 

The container is failing to start with below error
`s6-overlay-preinit: fatal: unable to mkdir /var/run/s6: Permission denied`

Reference to discussion forum on same issue: https://forum.posit.co/t/rstudio-server-in-kubernetes/195626/4

Can you help in addressing the issue.

### How to reproduce this bug?

```sh
Run a pod with above mentioned spec. The container fail to startup.
```

**Comment by nathanweeks** [comment]
The approach described in the Rocker [Singularity](https://rocker-project.org/use/singularity.html) guide, which calls `rserver` directly, could be adapted to run RStudio Server on Kubernetes with a non-root user.

Minimal example using a Pod (though StatefulSet would probably be a better choise), disregarding Ingress (or Gateway, etc.), persistent volume for /home/rstudio, and storing the password in a Secret (assuming authentication isn't handled at the Ingress layer):

```
apiVersion: v1
kind: Pod
metadata:
  name: rstudio
spec:
  securityContext:
    runAsUser: 1000
    runAsGroup: 1000
  containers:
    - name: rstudio
      image: ghcr.io/rocker-org/rstudio:4.4.2
      ports:
        - containerPort: 8787
      env:
        - name: USER
          value: rstudio
        - name: PASSWORD
          value: my-password
      volumeMounts:
        - name: rstudio-home
          mountPath: /home/rstudio
        - name: run
          mountPath: /run
        - name: var-lib-rstudio-server
          mountPath: /var/lib/rstudio-server
      securityContext:
        allowPrivilegeEscalation: false
      resources:  
        requests:
          memory: "200Mi"  
          cpu: "3000m"     
        limits:
          memory: "5000Mi"
      command: ["rserver", "--auth-none=0", "--auth-pam-helper-path=pam-helper", 
                           "--auth-stay-signed-in-days=30", "--auth-timeout-minutes=0",
                           "--server-user=rstudio"]
  volumes:
    - name: rstudio-home
      emptyDir: {}
    - name: run
      emptyDir: {}
    - name: var-lib-rstudio-server
      emptyDir: {}
```

Example: create the pod in the default namespace, and use port-forwarding to access:
```
kubectl apply -f rstudio.yaml
kubectl port-forward rstudio 8787
... point your web browser to http://localhost:8787, and log in with user "rstudio" and password "my-password" ...
```

**Comment by radhupr** [comment]
@nathanweeks Is it not possible to have persistent volumes in the setup? When I try to mount /home with persistent volume, it doesnt go through.

**Comment by benz0li** [comment]
@radhupr Check out [Zero to JupyterHub with Kubernetes](https://github.com/jupyterhub/zero-to-jupyterhub-k8s) + [Authentication](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/docs/source/administrator/authentication.md) + [JupyterLab R docker stack](https://github.com/b-data/jupyterlab-r-docker-stack)[^1].  
ℹ This allows you to mount the home directory (`/home/<username>`) on a per-user basis.

[^1]: Maybe the binder image of this repository works, too.

**Comment by nathanweeks** [comment]
> [@nathanweeks](https://github.com/nathanweeks) Is it not possible to have persistent volumes in the setup? When I try to mount /home with persistent volume, it doesnt go through.

Using a PV for `/home` should work in this case assuming `/home/rstudio` exists & is writable by the rstudio user when the "rstudio" container starts. But if the goal is a multi-user setup as described in #893, then @benz0li 's suggestion looks like it could be a more automated solution (though I'm not sure if/how it handles non-root containers, if that is a security requirement)?

On a somewhat-related note: it's possible for users to create on-demand non-root rstudio server containers with persistent-volume-backed home directories on an OpenShift cluster (example referenced here: https://github.com/rocker-org/rocker-versioned2/issues/747#issuecomment-2282305550).

**Comment by benz0li** [comment]
> though I'm not sure if/how it handles non-root containers

b-data's/my [Jupyter](https://github.com/b-data/jupyterlab-julia-docker-stack)[Lab](https://github.com/b-data/jupyterlab-mojo-docker-stack) [docker](https://github.com/b-data/jupyterlab-python-docker-stack) [stack](https://github.com/b-data/jupyterlab-r-docker-stack) containers – like the [Jupyter docker stacks](https://github.com/jupyter/docker-stacks) ones – run as non-`root` (`uid=1000(jovyan) gid=100(users)`) by default.

**Comment by perllaghu** [comment]
We have RStudio running in a kubernetes cluster, along-side other jupyter-based images - in our case, it's a our own image derived from `rocker/binder`

We renamed `/home/rstudio` to `/home/jovyan`, and linked `/home/studio` to `/home/jovyan`

We had some fun & games getting things to route through our various proxies..... but it was mostly a case of reading docs & not trying 3 changes at once :)

**Comment by cboettig** [comment]
Thanks @perllaghu !  The images in https://github.com/rocker-org/ml now take this strategy as well.  This is similar to the approach in rocker/binder but inherits directly from jupyter docker stack images.

**Comment by radhupr** [comment]
@perllaghu Could you give some information about yur setup in Kubernetes?
I'm using helm from  https://github.com/jupyterhub/zero-to-jupyterhub-k8s/ and changed the user image in values file as below to get what we wanted.
```
singleuser:
  image:
    name: glcr.b-data.ch/jupyterlab/r/tidyverse
    tag: "4.4.2"
```
But I have issues while processing big chunk of data in User's R studio session. The cpu usage goes very high and the session crashes. How have you been configuring or addressing file upload and big data processing in your setup?

**Comment by radhupr** [comment]
I wasnt setting the cmd for singleuser. I will set it and test. 
The fileupload is wokring. But its take a lot of time to download files from any remote url :( 

Data processing : 
The pod get cpu throttled if I set resource limits. But I tried to remove cpu limits and it consumes all of the cpu in the running server and the server crashes. I was wondering if there is any better solution for handling big data processing with this solution

**Comment by cboettig** [comment]
@radhupr are you setting memory limits? cpu use by itself rarely crashes a server, but can be correlated with RAM use.

**Comment by benz0li** [comment]
> I wasnt setting the cmd for singleuser. I will set it and test. The fileupload is wokring.

@radhupr Setting `singleuser.cmd: start-singleuser.sh` ensures that the startup scripts are run.  
ℹ For more information, see [JupyterLab R docker stack: Notes > Tweaks](https://github.com/b-data/jupyterlab-r-docker-stack/blob/main/NOTES.md#tweaks).
 
> Data processing : The pod get cpu throttled if I set resource limits. But I tried to remove cpu limits and it consumes all of the cpu in the running server and the server crashes. I was wondering if there is any better solution for handling big data processing with this solution

Use something like

```yaml
singleuser:
  cpu:
    limit: 2
    guarantee: 0.1
  memory:
    limit: 8G
```

to limit to 2 cores and 8 GB RAM. Adapt to your needs.

---

Default values:

> ```yaml
> singleuser:
>   cpu:
>     limit:
>     guarantee:
>   memory:
>     limit:
>     guarantee: 1G
> ```

– https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/d31863b6cf4f8674262690134de1e17132b8fc6a/jupyterhub/values.yaml#L426-L431

This means no CPU limit and no RAM limit. And @cboettig is right: If a pod uses up all RAM, the server (host) is at risk.
