### ISSUE TITLE
Persist installed packages

### ISSUE THREAD

**Issue by mindrunner** [rocker-org/rocker-versioned2#920]
`rstudio` installs packages to a folder in `/home/rstudio/R` which is impractical since the changes are lost after a container restart. If I try to bind mount that folder, `rstudio` decides to install packages somewhere else (`/usr/local/lib/....`).

What is the preferred way of persisting user packages?

**Comment by eddelbuettel** [comment]
There are two aspects to your question. First, how do set options during startup of R is described _exhaustively_ in the help page accessible via `help(Startup)` (and in other places).  There are different ways, my preference for site-wide settings is `/etc/R/Rprofile.site` (and `/etc/R/` is a convenience shortcut I create in `r-base-core`).

The second aspect is a bit more special and depends on exactly what you do / how you do it.  You absolutely can persist directories across restarts, it seems you know how, and now it is a matter of working through that locally, conditional on what you do in the first step.  You _should_ be able to make this work without altering the container but worst case you can always build a local container from ours and hard-code your settings.

**Comment by mindrunner** [comment]
Turned out that a typo in my compose file resulted in `rstudio` silently skipping my config due to a missing folder.

For reference, here is my setup:


.Renviron
``` 
R_LIBS=/home/rstudio/R/library
R_LIBS_USER=/home/rstudio/R/library
R_DEFAULT_PACKAGES='utils,grDevices,graphics,stats'
```

docker-compose.yml (simplified)
```
services:
  studio:
    image: rocker/rstudio:4
    restart: always
    ports:
      - 8787:8787
    environment:
      - "USERID=1002"
      - "GROUPID=1002"
    volumes:
      - ./config:/home/rstudio/.config/rstudio
      - ./workspace:/home/rstudio/workspace
      - ./library:/home/rstudio/R/library
      - ./.Renviron:/home/rstudio/.Renviron:ro
```


Thanks for your help @eddelbuettel
